exact_names = {
    'ami_megarac':   'AMI MegaRac Remote Management Default Cert (SSL)',
    'audiocodecs_8443': 'AudioCodecs MP serices 443/8443 Default Cert (SSL)',
    'avigilon':     'Aviligon Gateway Default cert',
    'avocent_1':     'Avocent Default cert (unknown device) (SSL)',
    'broadcom_1':    'Broadcom Generic Modem (SSL)',
    'canon_iradv':   'Canon IR-ADV Login Page (SSL/8443)',
    'ecessa':        'Ecessa PowerLink Wan Optimizer (SSL)',
    'edgewater_1':   'EdgeWater Networks VOIP Solution (SSL)',
    'enco_player_1': 'Enco Enplayer Default Cert (SSL)',
    'foscam_cam':    'Foscam IPcam Client Login (SSL)',
    'fujistu_celvin': 'Fujitsu Celvin NAS (SSL)',
    'hikvision':     'Hikvision Default Cert',
    'huawei_hg658':  'Huawei Home Gateway HG658d (SSL)',
    'interpeak_device': 'Something made by interpeak (SSL)',
    'lacie_1':       'LaCie CloudBox (SSL)',
    'lg_nas_1':      'LG NAS Device (SSL)',
    'lifesize_1':    'Lifesize Product (SSL)',
    'ligowave_1':    'LigoWave Default Cert (probably APC Propeller 5) (SSL)',
    'netgear_1':     'NetGear Default cert UTM  (SSL)',
    'nomadix_ag_1':  'Nomadix AG series Gateway (SSL)',
    'opengear_default_cert': 'Opengear Management Console Default cert (SSL)',
    'ubiquiti':      'Ubiquiti AirMax or AirFiber Device (SSL)',
    'verifone_sapphire': 'Verifone Sapphire Device (SSL)',
    'verizon_jungo': 'Verizon Jungo OpenRG product (SSL/8443)',
    'zyxel_pk5001z': 'Zyxel PK5001Z default cert (SSL)',
}

partial_names = {
    'axentra_1':     'Seagate/Axentra NAS Default Cert 863B4AB (443/SSL)',
    'buffalo_1':     'Buffalo Default Cert (443/SSL)',  
    'colubris':      'HPE MSM Series Device (SSL)',  
    'digi_int_1':    'Digi Passport Default Cert (443/SSL)',  
    'filemaker':     'Filemaker Secure Database Website (SSL)',  
    'intelbras_wom500': 'IntelBras Wom500 (admin/admin) (SSL)',  
    'ironport_device': 'Cisco IronPort Device Default SSL (443/SSL)',
    'meru_net_1':    'Meru Network Management Device  (443/SSL)',
    'netgear_2':     'Netgear Default Cert Home Router (8443/SSL)',  
    'netvanta':      'ADTRAN NetVanta Total Access Device (SSL)',  
    'prtg_network_monitor_1': 'Paessler PTRG Monitoring Default Cert(443/SSL)',      
    'qnap':         'QNAP NAS TS series detected (SSL)',
    'samsung':      'Unknown Samsung Device (SSL)',
    'supermicro_ipmi': 'Supermicro IPMI Default Certs (SSL)',  
    'UBNT':         'Ubiquiti AirMax or AirFiber Device (SSL)',
    'Vigor':        'DrayTek Vigor Device (SSL)',  
}
